recipe_tracking_project/recipe_app/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index),
    path('my_recipe_list', views.recipe_list),
    path('register', views.registration_display),
    path('register_attempt', views.register),
    path('login', views.login_display),
    path('login_attempt', views.login),
    path('add_recipe', views.add_recipe_display),
    path('add_recipe_attempt', views.add_recipe),
    path('user', views.UserView.as_view()),
    path('recipe', views.RecipeView.as_view()),
    path('user/list', views.UserListView.as_view()),
    path('recipe/list', views.RecipeListView.as_view())
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_tracking_project/recipe_tracking_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe_app.urls')),
]

recipe_tracking_project/recipe_app/models.py
from django.db import models
import re
import bcrypt
import datetime

from django.db.models.manager import EmptyManager

email_regex = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def registration_validator(self, postData):
        errors = {}
        if len(postData['first_name']) == 0:
            errors['first_name'] = "First name is required"
        elif len(postData['first_name']) < 2 or postData['first_name'].isalpha() != True:
            errors['first_name'] = "First name must be at least 2 characters, letters only"
        if len(postData['last_name']) == 0:
            errors['last_name'] = "Last name is required"
        elif len(postData['last_name']) < 2 or postData['last_name'].isalpha() != True:
            errors['last_name'] = "Last name must be at least 2 characters, letters only"
        if len(postData['email']) == 0:
            errors['email'] = "Email is required"
        elif not email_regex.match(postData['email']):
            errors['email'] = "Invalid email address"
        existing_user = User.objects.filter(email=postData['email'])
        if len(existing_user) > 0:
            errors['email'] = "Email already in use"
        if len(postData['password']) == 0:
            errors['password'] = "Password is required"
        elif len(postData['password']) < 8:
            errors['password'] = "Password must be at least 8 characters"
        elif postData['password'] != postData['confirm_password']:
            errors['password'] = "Passwords do not match"
        return errors
        
    def log_in_validator(self, postData):
        errors = {}
        existing_user = User.objects.filter(email=postData['email'])
        if len(postData['email']) == 0:
            errors['email'] = "Email is required"
        elif len(existing_user) != 1:
            errors['email'] = "User not found"
        if len(postData['password']) == 0:
            errors['password'] = "Password is required"
        if existing_user:
            if bcrypt.checkpw(postData['password'].encode(), existing_user[0].password.encode()) != True:
                errors['email'] = "Email and password do not match"
        return errors

class User(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class RecipeManager(models.Manager):
    def recipe_validator(self, postData):
        errors = {}
        if len(postData['title']) == 0:
            errors['title'] = 'Title is required'
        if len(postData['link_to_recipe']) == 0:
            errors['link_to_recipe'] = 'Link is required'
        elif len(postData[['link_to_recipe']]) < 6:
            errors['link_to_recipe'] = 'Link must be at least 6 characters'
        if len(postData['description']) == 0:
            errors['description'] = 'Description is required'
        current_date = datetime.date.today()
        if (postData['last_made_at']) > current_date:
            errors['last_made_at'] = 'Date cannot be in the future'

class Recipe(models.Model):
    MEAT_CHOICES = (
        ("RM", "Red Meat"),
        ("PL", "Poultry"),
        ("FI", "Fish"),
        ("VG", "Vegetarian"),
    )
    CATEGORY_CHOICES = (
        ("AM", "American"),
        ("CH", "Chinese"),
        ("EE", "Eastern European"),
        ("EN", "English"),
        ("FR", "French"),
        ("GE", "German"),
        ("GR", "Greek"),
        ("IN", "Indian"),
        ("IT", "Italian"),
        ("JP", "Japanese"),
        ("KR", "Korean"),
        ("MX", "Mexican"),
        ("OT", "Other"),
        ("SL", "Soul Food"),
    )
    title = models.CharField(max_length=90)
    picture = models.ImageField(upload_to="recipe_photo_album")
    link_to_recipe = models.URLField(max_length=200)
    description = models.TextField(blank=True)
    meat_type = models.CharField(max_length=2, choices=MEAT_CHOICES, default=MEAT_CHOICES[0][0])
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0])
    best_quantity = models.DecimalField(max_digits=3, decimal_places=2, default=1)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True)
    comments = models.TextField(blank=True)
    last_made_at = models.DateField()
    quick_and_easy = models.BooleanField(default=False)
    is_favorite = models.BooleanField(default=False)
    have_made_before = models.BooleanField(default=False)
    saved_by = models.ForeignKey(User, related_name='saved_recipes', on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = RecipeManager()

recipe_tracking_project/recipe_app/views.py
from django.http import request
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import *
from rest_framework import generics
from .serializers import UserSerializer, RecipeSerializer
import bcrypt

# Create your views here.
def index(request):
    return render(request, 'index.html')
    
def recipe_list(request):
    if 'user_id' in request.session:
        current_user = User.objects.get(id=request.session['user_id'])
        current_users_recipes = Recipe.objects.filter(saved_by=current_user)
        previously_made = current_users_recipes.filter(have_made_before=True)
        favorited_recipes = current_users_recipes.filter(is_favorite=True)
        saved_recipes = current_users_recipes.filter(have_made_before=False)
        context = {
            'user': current_user,
            'recipes': current_users_recipes,
            'have_made': previously_made,
            'favorite_recipes' : favorited_recipes,
            'saved_for_later' : saved_recipes,
        }
        return render(request, 'recipe_list.html', context)
    else:
        return redirect('/login')

def registration_display(request):
    return render(request, 'registration.html')

def register(request):
    if request.method == "POST":
        errors = User.objects.registration_validator(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value)
            return redirect ('/register_page')
        hashed_password = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt()).decode()
        new_user = User.objects.create(
            first_name = request.POST['first_name'],
            last_name = request.POST['last_name'],
            email = request.POST['email'],
            password = hashed_password
        )
        request.session['user_id'] = new_user.id
        return redirect('/my_recipe_list')
    return redirect('/register_page')

def login_display(request):
    return render(request, 'login.html')

def login(request):
    if request.method == "POST":
        errors = User.objects.log_in_validator(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value)
            return redirect('/login')
        this_user = User.objects.get(email=request.POST['email'])
        request.session['user_id'] = this_user.id
        return redirect('/my_recipe_list')
    
    return redirect('/login')

def add_recipe_display(request):
    return render(request, 'add_recipe.html')

def add_recipe(request):
    if request.method == "POST":
        errors = Recipe.objects.recipe_validator(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value)
            return redirect('/add_recipe')       
    return redirect('/my_recipe_list')

class UserView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class RecipeView(generics.CreateAPIView):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer

class UserListView(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class RecipeListView(generics.ListAPIView):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer

recipe_tracking_project/recipe_app/templates/add_recipe.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            {% load static %}
            <link rel="stylesheet" href="{% static 'style.css' %}">
            <!-- Bootstrap CDN -->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
            <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,500,700" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
            <title>Recipe App</title>
        </head>
        <body>
            <div class="container p-3">
                <h1 class="text-center mt-5">My Recipe Database</h1>
                <div id="register_form" class="container border rounded px-5 py-4 mt-3 mb-5 shadow" style="max-width: 400px;">
                    <h3 class="text-center mb-4">Add a recipe</h3>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <form action="/add_recipe_attempt" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="title" placeholder="Title">
                        </div>
                        <button class="btn btn-primary btn-block btn-lg shadow-lg my-3">Submit</button>
                    </form>
                </div>
            </div>
        </body>

recipe_tracking_project/recipe_app/templates/index.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            {% load static %}
            <link rel="stylesheet" href="{% static 'style.css' %}">
            <!-- Bootstrap CDN -->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
            <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,500,700" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
            <title>Recipe App</title>
        </head>
        <body>
            <div id="header" class="text-center">
                <h1 class="p-5">Welcome to Recipe Management App</h1>
            </div>
            <div id="recipe_display" class="text-center">
                <h1>Recipes</h1>
                {% for recipe in recipes %}
                <div class="recipes d-inline-block" id="recipe_{{ recipe.id }}">
                    <h3>{{ recipe.title }}</h3>
                    <img src="{{ recipe.picture.url }}" alt="recipe_img">
                    <h3>Meat: {{ recipe.get_meat_type_display }}</h3>
                    <h3>Category: {{ recipe.get_category_display }}</h3>
                    <h3>{{ recipe.description }}</h3>
                    <h3>Recipe saved by: {{ recipe.saved_by.first_name }} {{ recipe.saved_by.last_name }}</h3>
                </div>
                {% endfor %}
            </div>
        </body>

recipe_tracking_project/recipe_app/templates/login.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            {% load static %}
            <link rel="stylesheet" href="{% static 'style.css' %}">
            <!-- Bootstrap CDN -->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
            <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,500,700" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
            <title>Recipe App</title>
        </head>
        <body>
            <div class="container p-5">
                <h1 class="text-center mt-5">My Recipe Database</h1>
                <div class="container border rounded p-5 my-5 shadow" style="max-width: 400px;">
                    <h3 class="text-center mb-4">Sign In</h3>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <form action="/login_attempt" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" placeholder="Password">
                        </div>
                        <div class="custom-control custom-checkbox form-group">
                            <input type="checkbox" class="custom-control-input" id="remember_me">
                            <label for="remember_me" class="custom-control-label">Remember Me</label>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block btn-lg shadow-lg my-3">Sign In</button>
                        <p class="text-center">Not a member? <a class="text-primary" href="/register_page">Register</a></p>
                    </form>
                </div>
            </div>
        </body>

recipe_tracking_project/recipe_app/templates/recipe_list.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            {% load static %}
            <link rel="stylesheet" href="{% static 'style.css' %}">
            <!-- Bootstrap CDN -->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
            <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,500,700" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
            <title>Recipe App</title>
        </head>
        <body>
            <div id="header" class="text-center">
                <h1 class="p-5">{{ user.first_name }} {{ user.last_name }}'s Recipes</h1>
            </div>
            <div class="row">
                <div class="col px-5">
                    <div id="all_recipe_display">
                        <div id="card_holder" class="row p-3 mt-1">
                            {% for recipe in recipes %}
                            <div data-genre="{{ recipe.category }}" class="col-sm-6 col-lg-4 mb-4">
                                <a href="item/{{ recipe.id }}">
                                    <div id="recipe_cards" class="card h-100 shadow mx-2">
                                        <img src="{{ recipe.picture.url }}" alt="recipe_img" class="card-img-top pt-4 px-4">
                                        <div class="card-body text-center pb-3">
                                            <h4 class="card-title">{{ recipe.title }}</h4>
                                            <h4 class="card-text text-success">{{ recipe.category }}</h4>
                                            {% if recipe in favorite_recipes %}
                                                <i class="fas fa-star fa-2x text-warning"></i>
                                            {% endif %}
                                            {% if recipe in saved_for_later %}
                                                <i class="fas fa-flag fa-2x text-danger"></i>
                                            {% endif %}
                                        </div>
                                    </div>
                                </a>
                            </div>
                            {% empty %}
                            <h3 class="pt-5">Your recipe list is currently empty!</h3>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </body>

recipe_tracking_project/recipe_app/templates/registration.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            {% load static %}
            <link rel="stylesheet" href="{% static 'style.css' %}">
            <!-- Bootstrap CDN -->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
            <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,500,700" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
            <title>Recipe App</title>
        </head>
        <body>
            <div class="container p-3">
                <h1 class="text-center mt-5">My Recipe Database</h1>
                <div id="register_form" class="container border rounded px-5 py-4 mt-3 mb-5 shadow" style="max-width: 400px;">
                    <h3 class="text-center mb-4">Register</h3>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <form action="/register_attempt" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="first_name" placeholder="First Name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="last_name" placeholder="Last Name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password">
                        </div>
                        <button class="btn btn-primary btn-block btn-lg shadow-lg my-3">Register</button>
                        <p class="text-center">Have an account? <a class="text-primary" href="/login">Sign in</a></p>
                    </form>
                </div>
            </div>
        </body>